[build]
  publish = "."
  command = "echo 'No build process needed for static site'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/profile"
  to = "/#profile"
  status = 301

[[redirects]]
  from = "/achievements"
  to = "/#achievements"
  status = 301

[[redirects]]
  from = "/sport"
  to = "/#sport"
  status = 301

[[redirects]]
  from = "/partnership"
  to = "/#partnership"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/#contact"
  status = 301

# SPA fallback for any unmatched routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  HUGO_VERSION = "0.74.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "echo 'Deploy preview - no build needed'"

[context.branch-deploy]
  command = "echo 'Branch deploy - no build needed'"